<dl>
	<dt>Name</dt>
		<dd>$EnquiryName</dd>
	<dt>Company</dt>
		<dd>$EnquiryCompany</dd>
	<dt>Phone</dt>
		<dd>$EnquiryPhone</dd>
	<dt>Email</dt>
		<dd>$EnquiryEmail</dd>
	<dt>Subject</dt>
		<dd>$EnquirySubject</dd>
	<dt>Message</dt>
		<dd>$EnquiryMessage</dd>
</dl>